name: planetquiz
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  audioplayers: ^6.0.0
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0
  firebase_database: ^10.5.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  video_player: ^2.8.6
  gif: ^2.3.0
  animated_text_kit: ^4.2.2
  flutter_animated_button: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/Loss.json
    - assets/animations/Win.json
    - assets/AlverniaLogo.png
    - assets/Loga/
    - assets/animations/PQGIF.gif
    - assets/animations/FirstScreen.gif
    - assets/animations/QuizScreenBackground.gif
    - assets/animations/PQGIF2.gif

